# Generated by Django 4.2.7 on 2025-02-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0004_alter_contact_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
        migrations.AddField(
            model_name='contact',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
