# Generated by Django 4.2.7 on 2025-02-10 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0005_remove_contact_date_contact_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Date',
            new_name='date',
        ),
    ]
