# Generated by Django 4.2.7 on 2025-02-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0008_vehiclepass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclepass',
            name='photo',
        ),
        migrations.AddField(
            model_name='vehiclepass',
            name='aadhaar_back',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_photos/aadhaar_back/'),
        ),
        migrations.AddField(
            model_name='vehiclepass',
            name='aadhaar_front',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_photos/aadhaar_front/'),
        ),
        migrations.AddField(
            model_name='vehiclepass',
            name='license_photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_photos/license/'),
        ),
        migrations.AddField(
            model_name='vehiclepass',
            name='rc_book',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_photos/rc_book/'),
        ),
    ]
