# Generated by Django 4.2.7 on 2025-02-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0009_remove_vehiclepass_photo_vehiclepass_aadhaar_back_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('press_channel', models.CharField(max_length=255)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('press_id_card', models.ImageField(upload_to='press_id_cards/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Pending', max_length=10)),
            ],
        ),
    ]
