# Generated by Django 4.2.7 on 2025-02-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0010_presspass'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclepass',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
