# Generated by Django 4.2.7 on 2025-02-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0011_vehiclepass_reject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclepass',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclepass',
            name='serial_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
