# Generated by Django 4.2.7 on 2025-02-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0012_vehiclepass_issue_date_vehiclepass_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclepass',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='vehiclepass',
            name='serial_number',
        ),
    ]
