# Generated by Django 4.2.7 on 2025-02-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0013_remove_vehiclepass_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclepass',
            name='extra_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehiclepass',
            name='extra_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclepass',
            name='travel_reason',
            field=models.CharField(max_length=255),
        ),
    ]
