# Generated by Django 4.2.7 on 2025-02-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0014_vehiclepass_extra_name_vehiclepass_extra_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclepass',
            name='approved_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
