# Generated by Django 4.2.7 on 2025-02-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0015_vehiclepass_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclepass',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
