# Generated by Django 4.2.7 on 2025-02-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0016_vehiclepass_approved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclepass',
            name='pass_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
