# Generated by Django 4.2.7 on 2025-02-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0017_vehiclepass_pass_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('user1', 'User1')], default='user', max_length=10),
        ),
    ]
