# Generated by Django 4.2.7 on 2025-02-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0018_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovVehiclePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=15)),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('aadhaar_front', models.ImageField(blank=True, null=True, upload_to='vehicle_photos/aadhaar_front/')),
                ('aadhaar_back', models.ImageField(blank=True, null=True, upload_to='vehicle_photos/aadhaar_back/')),
                ('rc_book', models.ImageField(blank=True, null=True, upload_to='vehicle_photos/rc_book/')),
                ('license_photo', models.ImageField(blank=True, null=True, upload_to='vehicle_photos/license/')),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('travel_reason', models.CharField(max_length=255)),
                ('extra_name', models.CharField(blank=True, max_length=255, null=True)),
                ('extra_place', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_by', models.IntegerField(blank=True, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('pass_no', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
