# Generated by Django 4.2.7 on 2025-02-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0019_govvehiclepass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='govvehiclepass',
            name='extra_place',
        ),
    ]
