# Generated by Django 4.2.7 on 2025-02-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0020_remove_govvehiclepass_extra_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='govvehiclepass',
            name='aadhaar_back',
        ),
        migrations.RemoveField(
            model_name='govvehiclepass',
            name='aadhaar_front',
        ),
        migrations.RemoveField(
            model_name='govvehiclepass',
            name='license_photo',
        ),
        migrations.RemoveField(
            model_name='govvehiclepass',
            name='rc_book',
        ),
        migrations.AddField(
            model_name='govvehiclepass',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_photos/Gov_letter/'),
        ),
    ]
