# Generated by Django 4.2.7 on 2025-02-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0021_remove_govvehiclepass_aadhaar_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govvehiclepass',
            name='applied_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehiclepass',
            name='applied_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
