# Generated by Django 4.2.7 on 2025-02-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0022_alter_govvehiclepass_applied_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='govvehiclepass',
            name='other_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehiclepass',
            name='other_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
