# Generated by Django 4.2.7 on 2025-02-15 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0023_govvehiclepass_other_reason_vehiclepass_other_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='govvehiclepass',
            name='other_reason',
        ),
    ]
